const pantryTypes = {
	CREATE_PANTRY_ITEM: 'CREATE_PANTRY_ITEM',
	SET_QUERY: 'SET_QUERY',
	FILTER_PANTRY_CHIP: 'FILTER_PANTRY_CHIP',
	GET_PANTRY_DETAIL: 'GET_PANTRY_DETAIL',
};

export default pantryTypes